name: Build and test pull request
on: pull_request

jobs:
  build-and-test:
    runs-on: ubuntu-16.04
    
    steps:
    - name: Checkout last commit
      uses: actions/checkout@v1
    
    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    
    - name: Install dependencies
      run: npm ci

    - name: Build
      run: npm run build --if-present
        
    - name: Test with Jest
      run: npm run jest

    - name: Test with Cypress
      run: npm run e2e
